name: Tests
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    # container:
    #   image: cypress/browsers:latest
    #   options: --user 1001
    strategy:
      matrix:
        browser: ["chrome"]
        # browser: ["chrome", "firefox"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: canary
      - name: Cypress run with browser ${{ matrix.browser }}
        uses: cypress-io/github-action@master
        env:
          DEBUG: '@cypress/github-action'
          # DEBUG: 'cypress:*'
        with:
          install-command: bun install
          command: bun cypress run --browser ${{ matrix.browser }}
          # start: bun run cypress:open
          # wait-on: 'http://localhost:3000'
