name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    strategy:
      matrix:
        browser: ["chrome", "firefox"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: canary
      - name: Cypress run with browser ${{ matrix.browser }}
        with:
          start: cypress:open
          wait-on: 'http://localhost:3000'
          command: bunx cypress run -- --browser ${{ matrix.browser }}
