name: Tests
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    strategy:
      matrix:
        browser: ["chrome", "firefox"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Cypress run with browser ${{ matrix.browser }}
        uses: cypress-io/github-action@master
        with:
          browser: ${{ matrix.browser }}
          install-command: yarn install
